### ISSUE TITLE
Форматиране на текст в Библиоман

### ISSUE THREAD

**Issue by cattiva2511** [chitanka/biblioman#10]
Дали може в Библиоман за анотации, съдържание, информация за автора и т.н. полета да се ползва маркиращ език? (Нямам претенции какви маркери ще се ползват, каквито са удобни на всички.)

**Comment by bmanolov** [comment]
Какви маркери ще са нужни?

**Comment by cattiva2511** [comment]
Според мен html тагове ще са достатъчни, като напр.: <b></b, <i></i>
