### ISSUE TITLE
Войната на Квазичовекът

### ISSUE THREAD

**Issue by vladtk75** [chitanka/biblioman#2]
[Войната на Квазичовекът.pdf](https://github.com/chitanka/biblioman/files/1735017/default.pdf)
![book](https://user-images.githubusercontent.com/36606748/36355864-89aaa044-14f2-11e8-9758-7d55e1e99bb7.png)

**Comment by bmanolov** [comment]
Това не е за тук.

**Comment by vladtk75** [comment]
Как да вкарам книгата си в Библиоман?
Сигурно съм много прост.
Не ми се получава!

**Comment by bmanolov** [comment]
Книгата трябва да бъде издадена от някое издателство или от някой по-известен сайт. Едва след това може да се добави в Библиоман.
