### ISSUE TITLE
Публични рафтове

### ISSUE THREAD

**Issue by ventcis** [chitanka/biblioman#3]
Свързване на книгите с публичните рафтове.

**Comment by ventcis** [comment]
Всяка конкретна книга да има връзка с рафтовете и потребителите...
Пример с любими книги. Да се показват всички потребители, на които тази книга е любима. Освен това името на всеки потребител, от този списък, да води към всичките му любими книги. Бутончето над рафт (звездичката), може да е връзка към списъка с тези потребители. В момента тези бутончета (отметката и звездичката) и самите рафтове май дублират дейността си, служат само за маркиране...

**Comment by bmanolov** [comment]
Функционалността е реализирана.

Бутончетата отгоре (отметката и звездичката) дублират падащото меню, но са сложени за улеснение – те представят съответните важни рафтове на потребителя. По подразбиране в началото всеки потребител има само два важни рафта.
