### ISSUE TITLE
Програма за показване на djvu.

### ISSUE THREAD

**Issue by ventcis** [chitanka/biblioman#4]
Текущата програма визуализира бавно djvu-тата с OCR слой.

**Comment by bmanolov** [comment]
Можеш ли да ми пратиш примерен файл, за да тествам с него?

**Comment by ventcis** [comment]
В архива съм приложил две книги. Едната е 368 стр., а другата - 688.
Файловете, в чийто имена присъства авторът, са с текстов слой, останалите са без.
Архива се намира тук: https://www.dropbox.com/s/fyeapkyx7003uvd/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8%20%D0%B2%20djvu.zip?dl=0

**Comment by ventcis** [comment]
Да, файловете се намират [](url)
В архива има две книги, едната е 224 стр, а другата 6

**Comment by bmanolov** [comment]
Ето една алтернативна програма за показване на djvu:
- https://djvu.js.org
- https://github.com/RussCoder/djvujs

Изпробвах приложените файлове с нея и не забелязах забавяне.

**Comment by bmanolov** [comment]
Добавих програмата от https://djvu.js.org
