### ISSUE TITLE
Синхронизиране имената на авторите

### ISSUE THREAD

**Issue by ventcis** [chitanka/biblioman#6]
Очевидно е, че има автори, които се възприемат, от българските издателства, с различни имена. Пример: Чарлз Буковски и Чарлс Буковски... Та, притесненията на cromberg са, че когато ни натиснат записите ще е трудно да ги установим и уеднаквим...

Неговото предложение е:

(14.03.2018 21:52:16) cromberg:
Здр! Забелязах някои трудности в Библиоман, свързани с името на автора - при присъствие на няколко "форми" на името - примерно, както е указано Роберт Луис Стивънсън (Робърт Луис Стивънсън) - в https://biblioman.chitanka.info/books/4945.
Та, имам предложение.
Стивънсън се "среща" също като Робърт Луи Стивънсън, Робърт Стивенсън, Роберт Луис Стивънсън, Р. Л. Стивънсън, Роберт Луис Стефенсон, Р. Стифенсон, Р. Стевенсон, само Стивенсон и още няколко подобни. С Мандор вече сме се сблъсквали с този проблем и сме го разисквали - едно от решенията е за автор да се използва (и изписва)  т.н. "канонично" име - тоест строго определено, без значение какво пише в книгата. В случая това ще е "Робърт Луис Стивънсън", а формата под която е указан в изданието автора може да се отбелязва като "алтернативно" (по подобие на съществуващото сега поле за названието на книгата). Подобен подход позволява да не се хабят сили за създаване на някакъв сложен алгоритъм за "кръстосване" на множество имена на един автор, а относно потребителя - той едва ли ще тръгне да търси "Стифенсон", "Виктор Хюго", "Е. Пое" и много други подобни "бисерчета" или печатни грешки. Наистина, в някои книги имената на авторите са така интерпретирани, че човек трябва да е специалист, за да се досети за кой става въпрос, но мисля, никой не е отменил редакторската дейност в Библиоман.

**Comment by bmanolov** [comment]
Въведох възможност за създаване на връзки между различните изписвания на имената.

Процеса е следния:
1. Въвежда се основното име на личността.
2. Въвеждат се алтернативните имена на личността и се свързват с основното име чрез посочване на „Канонична личност“.

В момента „старшите редактори“ имат достъп до тази функционалност.
